version: '3'

# This file helps run services so we can run integration tests.

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    # Instead od using in-memory DB, we could also persist data:
    #   -sharedDb -dbPath /home/dynamodblocal/data/
    command: -jar DynamoDBLocal.jar -inMemory -port 8000

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
    volumes:
      - minio-data:/export
    command: server /export
    environment:
      MINIO_ACCESS_KEY: localS3Credentials
      MINIO_SECRET_KEY: localS3Credentials
    
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add openEo http://minio:9000 localS3Credentials localS3Credentials;
      /usr/bin/mc rm -r --force openEo/results;
      /usr/bin/mc mb openEo/results;
      /usr/bin/mc policy download openEo/results;
      exit 0;
      "


volumes:
  minio-data:
