version: '3'
# This file helps run services so we can run integration tests.
# For testing: docker-compose up --abort-on-container-exit --exit-code-from pytest
# To see exit code: echo Exit Code is %errorlevel%
# For usage: docker-compose up -d

services:

  pytest:
    build:
      context: .
      dockerfile: ./tests/Dockerfile.pytest
    command: bash -c "./wait-for-it.sh dynamodb:8000 -- && ./wait-for-it.sh minio:9000 -- && DYNAMODB_LOCAL_URL='http://dynamodb:8000' pytest -x"

  # workers:
  #   image: shopeneo/workers
  #   container_name: workers
  #   build:
  #     context: .
  #     dockerfile: workers/Dockerfile
  #   depends_on:
  #       - createbuckets
  #       - dynamodb
  #   environment:
  #     # SH details should be specified in .env file:
  #     SENTINELHUB_INSTANCE_ID: "${SENTINELHUB_INSTANCE_ID}"
  #     SENTINELHUB_LAYER_ID: "${SENTINELHUB_LAYER_ID}"
  #     # S3 details - in our case, we connect to minio container:
  #     DATA_AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
  #     DATA_AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  #     DATA_AWS_S3_ENDPOINT_URL: http://minio:9000
  #     DYNAMODB_LOCAL_URL: http://dynamodb:8000
