version: "2.4"
# This file helps run services so we can run integration tests.
# For testing: docker-compose up --abort-on-container-exit --exit-code-from pytest
# To see exit code: echo Exit Code is %errorlevel%
# For usage: docker-compose up -d

services:

  pytest:
    build:
      context: .
      dockerfile: ./tests/Dockerfile.pytest
    depends_on:
      dynamodb:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      DATA_AWS_S3_ENDPOINT_URL: http://minio:9000
      DYNAMODB_LOCAL_URL: http://dynamodb:8000
      SQS_LOCAL_URL: http://sqs:9324
      SH_CLIENT_ID: "${TESTS_SH_CLIENT_ID}"
      SH_CLIENT_SECRET: "${TESTS_SH_CLIENT_SECRET}"
      RESULTS_S3_BUCKET_NAME_MAIN: "${RESULTS_S3_BUCKET_NAME_MAIN}"
      RESULTS_S3_BUCKET_NAME_CREODIAS: "${RESULTS_S3_BUCKET_NAME_CREODIAS}"
      RESULTS_S3_BUCKET_NAME_USWEST: "${RESULTS_S3_BUCKET_NAME_USWEST}"
      RESULTS_S3_BUCKET_ACCESS_KEY_ID_MAIN: "${RESULTS_S3_BUCKET_ACCESS_KEY_ID_MAIN}"
      RESULTS_S3_BUCKET_ACCESS_KEY_ID_CREODIAS: "${RESULTS_S3_BUCKET_ACCESS_KEY_ID_CREODIAS}"
      RESULTS_S3_BUCKET_ACCESS_KEY_ID_USWEST: "${RESULTS_S3_BUCKET_ACCESS_KEY_ID_USWEST}"
      RESULTS_S3_BUCKET_SECRET_ACCESS_KEY_MAIN: "${RESULTS_S3_BUCKET_SECRET_ACCESS_KEY_MAIN}"
      RESULTS_S3_BUCKET_SECRET_ACCESS_KEY_CREODIAS: "${RESULTS_S3_BUCKET_SECRET_ACCESS_KEY_CREODIAS}"
      RESULTS_S3_BUCKET_SECRET_ACCESS_KEY_USWEST: "${RESULTS_S3_BUCKET_SECRET_ACCESS_KEY_USWEST}"
      LOGGING_LEVEL: CRITICAL
      USAGE_REPORTING_BASE_URL: "${USAGE_REPORTING_BASE_URL_TESTING}"
      USAGE_REPORTING_AUTH_URL: "${USAGE_REPORTING_AUTH_URL_TESTING}"
      USAGE_REPORTING_AUTH_CLIENT_ID: "${USAGE_REPORTING_AUTH_CLIENT_ID_TESTING}"
      USAGE_REPORTING_AUTH_CLIENT_SECRET: "${USAGE_REPORTING_AUTH_CLIENT_SECRET_TESTING}"
    command: bash -c "cd /tests/ && pytest -x"

