FROM python:3.6.8
ADD . /
RUN chmod +x download-process-definitions.sh
RUN ./download-process-definitions.sh
WORKDIR /tests
RUN pip3 install --upgrade pip
RUN pip3 install pipenv
RUN \
    cd ../rest && \
    pipenv install --system --deploy --dev