FROM python:3.9.13
ADD . /
RUN chmod +x download-process-definitions.sh
RUN ./download-process-definitions.sh
WORKDIR /tests
RUN pip3 install --upgrade pip
RUN pip3 install pipenv==2022.4.8
RUN \
    cd ../rest && \
    pipenv install --system --deploy --dev