name: Deploy testing
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

jobs:

  run-reusable-lint-and-test:
    uses: ./.github/workflows/reusable_lint_and_test.yaml
    secrets: inherit
  
  deploy-testing:
    needs: run-reusable-lint-and-test

    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    env:
      DEPLOYMENT_NAME: "testing"
      TESTING_ECR_REGISTRY: ${{ secrets.TESTING_EC2_ECR_REGISTRY }}
      TESTING_ECR_REGISTRY_IMAGE: ${{ secrets.TESTING_EC2_ECR_REGISTRY_IMAGE }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: configure aws access credentials
        run: |
          mkdir -p ~/.aws
          echo -e "[default]\nregion=eu-central-1" > ~/.aws/config
          echo -e "[default]\naws_access_key_id=${{ secrets.TESTINGZAPPA_AWS_ACCESS_KEY_ID }}\naws_secret_access_key=${{ secrets.TESTINGZAPPA_AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials

      - name: install pipenv and aws
        run: |
          pip install pipenv==2021.5.29
          pip install awscli --no-build-isolation

      - name: download process definitions
        run: |
          chmod +x download-process-definitions.sh
          ./download-process-definitions.sh
      
      - name: install dependencies needed for deployment
        working-directory: ./rest
        run: pipenv install --dev

      - name: build docker image with correct tags
        working-directory: ./rest
        run: docker build -t "$TESTING_ECR_REGISTRY/$TESTING_ECR_REGISTRY_IMAGE:$GITHUB_REF_NAME" -t "$TESTING_ECR_REGISTRY/$TESTING_ECR_REGISTRY_IMAGE:latest" --build-arg VERSION=$GITHUB_REF_NAME --build-arg VCS_REF=$GITHUB_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') .

      - name: login for AWS ECR docker
        working-directory: ./rest
        run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin "$TESTING_ECR_REGISTRY"
      
      - name: push docker images (versioned with CI tag and "latest") to AWS ECR with docker
        working-directory: ./rest
        run: |
          docker push "$TESTING_ECR_REGISTRY/$TESTING_ECR_REGISTRY_IMAGE:$GITHUB_REF_NAME"
          docker push "$TESTING_ECR_REGISTRY/$TESTING_ECR_REGISTRY_IMAGE:latest"
